plugins {
  id 'java'
}

ext {
  // Dependency versions
  clthVersion = "2.1"
}

subprojects {
  java {
    sourceCompatibility = '25'
    targetCompatibility = '25'
  }
}

if (JavaVersion.current().isJava8Compatible()) {
  allprojects {
    tasks.withType(Javadoc).tap {
      configureEach {
        options.addStringOption('Xdoclint:none', '-quiet')
      }
    }
  }
}
