.bitmap sub-left
  ....xxxx.......
  .xxxxxxxxxxx.xx
  xxxxxxx*xxxxxxx
  .xxxxxxxxxxx.xx

.bitmap sub-right
  .......xxxx....
  xx.xxxxxxxxxxx.
  xxxxxxx*xxxxxxx
  xx.xxxxxxxxxxx.

.bitmap ship-left
  .....xxxx......
  .....xxxx......
  xxxxxxx*x..xxxx
  .xxxxxxxxxxxxxx
  ..xxxxxxxxxxxxx

.bitmap ship-right
  ......xxxx.....
  ......xxxx.....
  xxxx..x*xxxxxxx
  xxxxxxxxxxxxxx.
  xxxxxxxxxxxxx..

.bitmap depthcharge-1
  xxx
  x*x
  ...
  
.bitmap depthcharge-2
  xx.
  x*x
  .xx
  
.bitmap depthcharge-3
  xx.
  x*.
  xx.
  
.bitmap depthcharge-4
  .xx
  x*x
  xx.
