.bitmap sub-left
  ....xxxx.......
  .xxxxxxxxxxx.xx
  xxxxxxx*xxxxxxx
  .xxxxxxxxxxx.xx

.bitmap sub-right
  .......xxxx....
  xx.xxxxxxxxxxx.
  xxxxxxx*xxxxxxx
  xx.xxxxxxxxxxx.

.bitmap sub-left-explosion-1
  ....xxxxx.......
  .xxxx...xxxxxxxx
  xx..........x..x
  x......+.......x
  xx..........x..x
  .xxxxxxxxxxxxxxx

.bitmap sub-right-explosion-1
  .......xxxxx....
  xxxxxxxx...xxxx.
  x..x..........xx
  x.......+......x
  x..x..........xx
  xxxxxxxxxxxxxxx.

.bitmap sub-left-explosion-2
  ....xxx.xxx.......
  .xx.x.....xxx.xxxx
  xx...............x
  x................x
  ........+.........
  x................x
  xx...............x
  .xxx.xxxxxxxx.xxxx

.bitmap sub-right-explosion-2
  .......xxx.xxx....
  xxxx.xxx.....x.xx.
  x...............xx
  x................x
  .........+........
  x................x
  x...............xx
  xxxx.xxxxxxxx.xxx.

.bitmap sub-left-explosion-3
  .....xx..xx..........
  ......xxxx......xx...
  .x............xxx....
  xx...................
  .....................
  ...................xx
  ..........+........x.
  ...................xx
  .....................
  xx...................
  .x............xxx....
  ......xxxx......xx...
  .....xx..xx..........

.bitmap sub-right-explosion-3
  ..........xx..xx.....
  ...xx......xxxx......
  ....xxx............x.
  ...................xx
  .....................
  xx...................
  .x........+..........
  xx...................
  .....................
  ...................xx
  ....xxx............x.
  ...xx......xxxx......
  ..........xx..xx.....

.bitmap ship-left
  .....xxxx......
  .....xxxx......
  xxxxxxx*x..xxxx
  .xxxxxxxxxxxxxx
  ..xxxxxxxxxxxxx

.bitmap ship-right
  ......xxxx.....
  ......xxxx.....
  xxxx..x*xxxxxxx
  xxxxxxxxxxxxxx.
  xxxxxxxxxxxxx..

.bitmap depthcharge-1
  xxx
  x*x
  ...
  
.bitmap depthcharge-2
  xx.
  x*x
  .xx
  
.bitmap depthcharge-3
  xx.
  x*.
  xx.
  
.bitmap depthcharge-4
  .xx
  x*x
  xx.
